# Generated by Django 6.0.6 on 2026-07-16 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0002_prediccionmateria_delete_prediccionacademica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediccionmateria',
            old_name='calificacion_tercer_parcial_estimada',
            new_name='calificacion_final_maxima',
        ),
        migrations.AddField(
            model_name='prediccionmateria',
            name='calificacion_final_media',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='prediccionmateria',
            name='calificacion_final_minima',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='prediccionmateria',
            name='calificacion_maxima_tercer_parcial',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='prediccionmateria',
            name='calificacion_media_tercer_parcial',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='prediccionmateria',
            name='calificacion_minima_tercer_parcial',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
