# Generated by Django 6.0.6 on 2026-07-16 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predicciones', '0003_rename_calificacion_tercer_parcial_estimada_prediccionmateria_calificacion_final_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionmateria',
            name='margen_error_modelo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
