# Generated by Django 6.0.6 on 2026-07-06 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100)),
                ('area_materia', models.CharField(max_length=100)),
                ('grado', models.PositiveSmallIntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero')])),
                ('dificultad_materia', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('horas_clase_semana', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'unique_together': {('nombre_materia', 'grado')},
            },
        ),
    ]
